### ISSUE TITLE
1.7.0 - Can't seem to read signals

### ISSUE THREAD

**Issue by altmank** [notnotmelon/fluid-memory-storage#3]
Hey, thanks for creating this mod! Sorry to come with a bug/question but I can't seem to get any signal outputs from the top circle connection point of the fluid storage. Can you let me know if I'm doing something wrong or missing something?

![image](https://github.com/user-attachments/assets/560f7d46-c3a6-4907-a329-9b553166c864)
![image](https://github.com/user-attachments/assets/44622626-f3c8-4dfb-a8e3-4eafe7b30748)

**Comment by subtogash** [comment]
The same bug, but I have another bug, it is that I cannot place Fluid Storage with fluid in it, is says "no fluid storage" (or someone else (I can't check it right now))
